Network:
 epochs: 200
 batch_size: 50
 n_steps: 8
 dataset: "MNIST"
 rule: "TSSLBP"
 data_path: "/data/rboone/datasets/mnist"
 lr: 0.0005
 loss: "count"
 n_class: 10
 desired_count: 7.416
 undesired_count: .15352
 tau_m: 7.327
 tau_s: 1.595
 model: "LIF"
 a: .3996
 val_size: 0.1


Layers:
 conv_1:
   type: "conv"
   in_channels: 1
   out_channels: 15
   kernel_size: 5
   weight_scale: 1
   padding: 0
   threshold: 1


 pooling_1:
   type: "pooling"
   kernel_size: 2
   threshold: 1


 conv_2:
   type: "conv"
   in_channels: 15
   out_channels: 40
   kernel_size: 5
   weight_scale: 1
   padding: 0
   threshold: 1


 pooling_2:
   type: "pooling"
   kernel_size: 2
   threshold: 1


 FC_1:
   type: "linear"
   n_inputs: 640
   n_outputs: 300
   weight_scale: 1
   threshold: 1


 output:
   type: "linear"
   n_inputs: 300
   n_outputs: 10
   weight_scale: 1
   threshold: 1